foo: wulicloud-provider-mem-dev.v10
server:
  port: 9012

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: wulis.rabbitmq
    port: 5672
    username: Wulis
    password: Wulis

  redis:
    host: wulis.redis
    password: Wulis
    port: 6379
    jedis:
      pool:
        max-idle: 100           # 最大空闲数
        min-idle: 1             # 资源池确保最少空闲的连接数 默认值0
        max-wait: -1
        max-active: 1000
    timeout: 10000              # 客户端超时时间单位是毫秒 默认是2000

  sleuth:
    sampler:
      probability: 1.0                    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://wulis.zipkin:9411    # 指定了 Zipkin 服务器的地址
    sender:
      type: web                           # 发送给zipkin方式：rabbit或web(http)

  datasource:
    name: member
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://wulis.mysql:3306/wulicloud_member?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useCursorFetch=true&defaultFetchSize=100
      username: root
      password:            #请联系管理员WuliGao
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml  # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wulis.provider.**.model  # 注意：对应实体类的路径

# Mapper4
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  check-example-entity-class: true   # 校验误操作错误表
  safe-delete: true                    # 配置为 true 后，delete 和 deleteByExample 都必须设置查询条件才能删除，否则会抛出异常。
  safe-update: true                    # 配置为 true 后，updateByExample 和 updateByExampleSelective 都必须设置查询条件才能删除，否则会抛出异常（org.apache.ibatis.exceptions.PersistenceException）。

#pagehelper
pagehelper:
  helperDialect: mysql  # 数据库类型
  reasonable: true      # pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  supportMethodsArguments: true
  params: count=countSql

# 暴露所有端口和接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:          # 健康检查
      show-details: ALWAYS

# 开启hystrix熔断
feign:
  hystrix:
    enabled: true

# Swagger API信息说明
swagger:
  title: 会员中心API
  description: 会员中心接口文档说明
  version: 1.0v
  license:
  licenseUrl:
  contactName: WuliBao
  contactUrl: www.wulis.com
  contactEmail: 1435468902@qq.com